add_space: false
algo_reason: false
always_save_checkpoint: false
backend: nccl
batch_size: 256
beta1: 0.9
beta2: 0.99
bias: false
binary: false
block_size: 256
ckpt_path_name: ckpt_10000.pt
compile: false
data_format: plain
data_ratio: 0.2
data_shuffle: true
data_type: text
dataset: bal
decay_lr: true
device: cpu
dropout: 0.2
dtype: float16
eps: 0
eval_addition: true
eval_addition_ar: false
eval_addition_train: false
eval_interval: 250
eval_iters: 200
eval_only: false
eval_other: false
eval_text: false
eval_text_data_path: null
exp_name: addition-bal
grad_clip: 1.0
gradient_accumulation_steps: 1
init_from: scratch
learning_rate: 0.001
log_interval: 10
lr_decay_iters: 5000
max_iters: 5000
meta_path_specified: true
min_lr: null
multi_digit: false
n_embd: 384
n_head: 6
n_layer: 6
num_digit: 5
operator: +
other_operator: +
out_dir: out/addition_plain
print_interval: 2
random_A: false
random_C: false
result_dir: out/addition_plain/addition-bal
resume_dir: null
resume_iter: false
reverse_ab: false
reverse_c: false
save_final: true
simple: false
start: FILE:data/bal/test_10000.txt
start_ar: null
start_other: null
start_train: null
test_batch_size: 128
tokenizer: char
train_both: false
train_data_path: train_3digit_10000.txt
train_data_path2: train_addition.bin
use_flash: true
use_lora: false
val_data_path: val.bin
val_data_path2: val_addition.bin
vocabulary: all_ascii_chars
wandb_entity: cis7000_project1
wandb_log: true
wandb_project: addition
wandb_run_name: addition-bal
warmup_iters: 100
weight_decay: 0.1
zero_pad: false
